const express = require('express');
const router = express.Router();
const { getEmployees, createEmployee, registerFace, setEmployeePin, deleteEmployee, getAllEmployeesForFaceLogin, verifyEmployeePin } = require('../controllers/employee.controller.js');
const { protect } = require('../middleware/auth.middleware.js');
router.get('/face-login-data/:kioskId', getAllEmployeesForFaceLogin);
router.post('/verify-pin', verifyEmployeePin);
router.route('/').get(protect, getEmployees).post(protect, createEmployee);
router.route('/face').post(protect, registerFace);
router.route('/:id/set-pin').put(protect, setEmployeePin);
router.route('/:id').delete(protect, deleteEmployee);
module.exports = router;
